name: Bug Report
description: Report a bug.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help identify and fix the bug.
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: When I click here this happens
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this bug!.
