name: New feature
description: Request a new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly describe the new feature.
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      placeholder: A button in the screen X that allows to do Y
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion!